import * as React from 'react';

import { View } from 'react-native';

import { BrandMark } from '@/components/blocks/brand-mark';
import { Image } from '@/components/ui/image';
import { Text } from '@/components/ui/text';
import { Defs, RadialGradient, Rect, Stop, Svg } from '@/lib/svg-shim';

type MatchDetailPosterMetric = {
  label: string;
  value: string | number;
  delta?: string;
};

type MatchDetailPosterComparison = {
  label: string;
  /** Raw player value retained for callers; the poster shows it in the summary card. */
  value: string | number;
  delta: string;
  /** Filled portion of the comparison bar, from 0 to 100. */
  playerPercent: number;
  /** Benchmark marker position, from 0 to 100. */
  benchmarkPercent: number;
};

type MatchDetailPosterMoment = {
  /** Deprecated visual hint kept for backwards compatibility; the poster uses a typographic marker. */
  icon?: string;
  label: string;
  value: string | number;
  description?: string;
  /** Deprecated image slot kept for backwards compatibility. */
  imageUrl?: string;
};

type MatchDetailPosterBadgeTone = 'positive' | 'negative' | 'neutral' | 'accent';

type MatchDetailPosterBadge = {
  label: string;
  value?: string | number;
  tone?: MatchDetailPosterBadgeTone;
};

type MatchDetailPosterInsight = {
  /** Conclusion text shown in the insight pill. */
  text: string;
  /** Optional explicit color, e.g. rgb(34, 255, 197) or #22ffc5. */
  color?: string;
  /** Optional semantic fallback when color is not provided. */
  tone?: MatchDetailPosterBadgeTone;
};

type MatchDetailPosterLabels = {
  /** Section title for lobby comparisons. */
  vsLobby?: string;
  /** Section title for match moments. */
  matchMoments?: string;
};

type MatchDetailPosterProps = {
  /** Footer brand wordmark rendered with the shared VALPRO brand-mark logic. */
  brandLabel?: string;
  /** Match result callout, e.g. `"VICTORY"`. */
  outcomeLabel: string;
  /** Matches MatchCard result semantics: win, loss, or a neutral draw. */
  result?: 'win' | 'loss' | 'draw';
  /** Left score in the hero row. */
  myTeamScore: number;
  /** Right score in the hero row. */
  enemyTeamScore: number;
  /** Map and mode shown in the left side of the poster header. */
  mapName: string;
  modeLabel: string;
  /** Match duration shown with the date in the right side of the poster header. */
  durationLabel: string;
  /** Optional date shown in the top-right metadata block. */
  dateLabel?: string;
  /** Optional competitive tier colour applied to the rank label. */
  rankColor?: string;
  /** Optional rank / queue label shown above the date. */
  rankLabel?: string;
  /** Optional map splash art rendered behind the poster content. */
  mapBackgroundUrl?: string;
  /** Kept for backwards compatibility. The new layout uses the agent icon. */
  agentPortraitUrl?: string;
  /** Small agent icon shown beside the player identity. */
  agentIconUrl: string;
  /** Agent display name in the player identity block. */
  agentName: string;
  /** Player name/tag shown in the player identity block. */
  playerTag: string;
  /** Highlight KDA block. */
  kills: number;
  deaths: number;
  assists: number;
  /** First deaths, sourced from the match combat stats (`FD`). */
  firstDeaths?: number;
  /** Core metric row, typically ACS / ADR / HS% / KAST. */
  primaryMetrics: MatchDetailPosterMetric[];
  /** Additional metrics retained for existing callers and moment fallbacks. */
  secondaryMetrics: MatchDetailPosterMetric[];
  /** Optional benchmark rows. When omitted, the comparison panel is hidden. */
  comparisons?: MatchDetailPosterComparison[];
  /** Optional highlight cards, based on the app's match moments / multikills. */
  moments?: MatchDetailPosterMoment[];
  /** Optional conclusion labels. These are preferred over raw stat badges. */
  insights?: MatchDetailPosterInsight[];
  /** Backwards-compatible raw badge input; converted to compact conclusions when insights is absent. */
  badges?: Array<MatchDetailPosterBadge | string>;
  /** Optional translations for labels generated by the poster itself. */
  labels?: MatchDetailPosterLabels;
  /** Override the default 1080px canvas width. */
  width?: number;
  /** Override the default 1920px canvas height. */
  height?: number;
};

const BACKGROUND = 'rgb(8, 14, 18)';
const TEXT_PRIMARY = 'rgb(237, 233, 226)';
const TEXT_MUTED = 'rgba(237, 233, 226, 0.62)';
const VALPRO_RED = 'rgb(255, 70, 85)';
const WIN_ACCENT = 'rgb(34, 255, 197)';
const LOSS_ACCENT = VALPRO_RED;
const DRAW_ACCENT = 'rgb(240, 203, 116)';
const CARD_BACKGROUND = 'rgba(21, 24, 26, 0.72)';

function withAlpha(color: string, alpha: number): string {
  if (color.startsWith('rgb(')) {
    return color.replace('rgb(', 'rgba(').replace(')', `, ${alpha})`);
  }

  if (/^#[0-9a-f]{6}$/i.test(color)) {
    const red = Number.parseInt(color.slice(1, 3), 16);
    const green = Number.parseInt(color.slice(3, 5), 16);
    const blue = Number.parseInt(color.slice(5, 7), 16);
    return `rgba(${red}, ${green}, ${blue}, ${alpha})`;
  }

  return color;
}

function clampPercent(value: number): number {
  return Math.min(100, Math.max(0, value));
}

function getDeltaColor(delta: string): string {
  if (delta.startsWith('+')) return WIN_ACCENT;
  if (delta.startsWith('-')) return VALPRO_RED;
  return DRAW_ACCENT;
}

function normalizeBadge(badge: MatchDetailPosterBadge | string): MatchDetailPosterBadge {
  return typeof badge === 'string' ? { label: badge, tone: 'neutral' } : badge;
}

function getBadgeColor(tone: MatchDetailPosterBadgeTone = 'neutral', accentColor: string): string {
  if (tone === 'positive') return WIN_ACCENT;
  if (tone === 'negative') return VALPRO_RED;
  if (tone === 'accent') return accentColor;
  return DRAW_ACCENT;
}

function ComparisonBar({
  playerPercent,
  benchmarkPercent,
}: {
  playerPercent: number;
  benchmarkPercent: number;
}) {
  const player = clampPercent(playerPercent);
  const benchmark = clampPercent(benchmarkPercent);
  const isAhead = player > benchmark;
  const isBehind = player < benchmark;

  return (
    <View
      style={{
        flex: 1,
        height: 22,
        position: 'relative',
        overflow: 'hidden',
        borderRadius: 999,
        backgroundColor: 'rgba(255, 255, 255, 0.15)',
      }}>
      <View
        style={{
          position: 'absolute',
          top: 0,
          bottom: 0,
          left: 0,
          width: `${player}%`,
          borderRadius: 999,
          backgroundColor: isAhead ? WIN_ACCENT : isBehind ? VALPRO_RED : DRAW_ACCENT,
          opacity: 0.82,
        }}
      />
      <View
        style={{
          position: 'absolute',
          top: -3,
          bottom: -3,
          left: `${benchmark}%`,
          width: 4,
          borderRadius: 2,
          backgroundColor: TEXT_PRIMARY,
        }}
      />
    </View>
  );
}

function SectionLabel({ children }: { children: React.ReactNode }) {
  return (
    <Text
      style={{
        marginBottom: 15,
        color: TEXT_MUTED,
        fontSize: 22,
        lineHeight: 26,
        fontWeight: '800',
        letterSpacing: 4.8,
      }}>
      {children}
    </Text>
  );
}

function SummaryCard({
  stats,
}: {
  stats: MatchDetailPosterMetric[];
}) {
  return (
    <View
      style={{
        borderRadius: 31,
        overflow: 'hidden',
        backgroundColor: CARD_BACKGROUND,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.16)',
      }}>
      <View style={{ flexDirection: 'row', paddingVertical: 26, paddingHorizontal: 18 }}>
        {stats.map((stat, index) => (
          <View
            key={`${stat.label}-${index}`}
            style={{
              flex: 1,
              alignItems: 'center',
              justifyContent: 'center',
              borderLeftWidth: index === 0 ? 0 : 1,
              borderLeftColor: 'rgba(255, 255, 255, 0.15)',
            }}>
            <Text
              style={{
                color: TEXT_PRIMARY,
                fontSize: 46,
                lineHeight: 51,
                fontWeight: '800',
                letterSpacing: -1.5,
                fontVariant: ['tabular-nums'],
              }}>
              {stat.value}
            </Text>
            <Text
              style={{
                marginTop: 6,
                color: TEXT_MUTED,
                fontSize: 17,
                lineHeight: 20,
                fontWeight: '600',
                letterSpacing: 2.4,
              }}>
              {stat.label}
            </Text>
          </View>
        ))}
      </View>
    </View>
  );
}

function ComparisonCard({
  comparisons,
}: {
  comparisons: MatchDetailPosterComparison[];
}) {
  return (
    <View
      style={{
        paddingVertical: 26,
        paddingHorizontal: 29,
        borderRadius: 31,
        backgroundColor: 'rgba(21, 24, 26, 0.66)',
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.15)',
      }}>
      {comparisons.map((comparison, index) => (
        <View
          key={`${comparison.label}-${index}`}
          style={{
            flexDirection: 'row',
            alignItems: 'center',
            minHeight: 59,
            marginBottom: index === comparisons.length - 1 ? 0 : 9,
          }}>
          <Text
            style={{
              width: 90,
              color: TEXT_MUTED,
              fontSize: 20,
              lineHeight: 24,
              fontWeight: '600',
              letterSpacing: 1.3,
            }}>
            {comparison.label}
          </Text>
          <View style={{ flex: 1, flexDirection: 'row', alignItems: 'center', gap: 13 }}>
            <ComparisonBar
              playerPercent={comparison.playerPercent}
              benchmarkPercent={comparison.benchmarkPercent}
            />
            <Text
              style={{
                width: 84,
                color: getDeltaColor(comparison.delta),
                textAlign: 'right',
                fontSize: 21,
                lineHeight: 25,
                fontWeight: '600',
                fontVariant: ['tabular-nums'],
              }}>
              {comparison.delta}
            </Text>
          </View>
        </View>
      ))}
    </View>
  );
}

function MomentCard({
  moment,
  accentColor,
}: {
  moment: MatchDetailPosterMoment;
  accentColor: string;
}) {
  return (
    <View
      style={{
        flex: 1,
        minHeight: 156,
        padding: 22,
        borderRadius: 26,
        backgroundColor: 'rgba(21, 24, 26, 0.7)',
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.15)',
      }}>
      <View style={{ flexDirection: 'row', alignItems: 'center', gap: 13 }}>
        <View
          style={{
            width: 6,
            height: 26,
            borderRadius: 3,
            backgroundColor: accentColor,
            opacity: 0.82,
          }}
        />
        <Text
          style={{
            flex: 1,
            color: TEXT_MUTED,
            fontSize: 20,
            lineHeight: 24,
            fontWeight: '600',
            letterSpacing: 1.7,
          }}>
          {moment.label}
        </Text>
      </View>
      <Text
        style={{
          marginTop: 14,
          color: TEXT_PRIMARY,
          fontSize: 37,
          lineHeight: 42,
          fontWeight: '800',
          fontVariant: ['tabular-nums'],
        }}>
        {moment.value}
      </Text>
      {moment.description ? (
        <Text
          style={{
            marginTop: 7,
            color: TEXT_MUTED,
            fontSize: 18,
            lineHeight: 22,
            fontWeight: '600',
          }}>
          {moment.description}
        </Text>
      ) : null}
    </View>
  );
}

/**
 * Match-detail share poster inspired by a post-match performance recap.
 * It keeps the original MatchDetailPoster data contract while adding the
 * compact scoreboard hierarchy: summary stats, lobby benchmark bars, moments,
 * and derived performance insights. Summary values are intentionally shown
 * only once; the lobby panel focuses on relative position and delta.
 */
function MatchDetailPoster({
  brandLabel = 'VALPRO',
  outcomeLabel,
  result = 'win',
  myTeamScore,
  enemyTeamScore,
  mapName,
  modeLabel,
  durationLabel,
  dateLabel,
  rankColor,
  rankLabel,
  mapBackgroundUrl,
  agentIconUrl,
  agentName,
  playerTag,
  kills,
  deaths,
  assists,
  firstDeaths,
  primaryMetrics,
  secondaryMetrics,
  comparisons,
  moments,
  insights,
  badges,
  labels,
  width = 1080,
  height = 1920,
}: MatchDetailPosterProps) {
  const accentColor = result === 'win' ? WIN_ACCENT : result === 'loss' ? LOSS_ACCENT : DRAW_ACCENT;
  const summaryStats = primaryMetrics
    .filter((metric) => ['ACS', 'ADR', 'HS%', 'KAST'].includes(metric.label.toUpperCase()))
    .slice(0, 4);
  const fallbackMoments: MatchDetailPosterMoment[] = secondaryMetrics
    .slice(0, 4)
    .map((metric) => ({
      label: metric.label,
      value: metric.value,
    }));
  const visibleMoments = moments?.length ? moments.slice(0, 4) : fallbackMoments;
  const hasComparisons = Boolean(comparisons?.length);
  const visibleInsights: MatchDetailPosterInsight[] = insights?.length
    ? insights.slice(0, 4)
    : badges?.slice(0, 4).map((badge) => {
        const normalized = normalizeBadge(badge);
        return {
          text: normalized.value === undefined ? normalized.label : `${normalized.label} ${normalized.value}`,
          tone: normalized.tone,
        };
      }) ?? [];
  const hasInsights = visibleInsights.length > 0;
  return (
    <View
      style={{
        width,
        height,
        position: 'relative',
        overflow: 'hidden',
        backgroundColor: BACKGROUND,
      }}>
      {mapBackgroundUrl ? (
        <Image
          source={mapBackgroundUrl}
          accessibilityLabel={`${mapName} background`}
          style={{ position: 'absolute', top: 0, right: 0, bottom: 0, left: 0, opacity: 0.4 }}
          contentFit="cover"
        />
      ) : null}
      <View
        pointerEvents="none"
        style={{
          position: 'absolute',
          top: 0,
          right: 0,
          bottom: 0,
          left: 0,
          backgroundColor: 'rgba(4, 8, 11, 0.38)',
        }}
      />
      <View
        pointerEvents="none"
        style={{
          position: 'absolute',
          top: height * 0.12,
          left: -width * 0.1,
          width: width * 1.2,
          height: width * 1.2,
        }}>
        <Svg width="100%" height="100%">
          <Defs>
            <RadialGradient id="matchDetailPosterGlow" cx="0.5" cy="0.5" r="0.5">
              <Stop offset="0" stopColor={accentColor} stopOpacity="0.08" />
              <Stop offset="0.5" stopColor={accentColor} stopOpacity="0.025" />
              <Stop offset="1" stopColor={accentColor} stopOpacity="0" />
            </RadialGradient>
          </Defs>
          <Rect x="0" y="0" width="100%" height="100%" fill="url(#matchDetailPosterGlow)" />
        </Svg>
      </View>
      <View
        style={{
          position: 'absolute',
          top: 0,
          left: 0,
          width,
          height,
          paddingTop: 64,
          paddingRight: 84,
          paddingBottom: 64,
          paddingLeft: 84,
        }}>
        <View style={{ flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' }}>
          <View>
            <Text
              style={{
                color: accentColor,
                fontSize: 33,
                lineHeight: 37,
                fontWeight: '900',
                letterSpacing: 3.7,
              }}>
              {outcomeLabel}
            </Text>
            <Text
              style={{
                marginTop: 14,
                color: TEXT_MUTED,
                fontSize: 20,
                lineHeight: 24,
                fontWeight: '800',
                letterSpacing: 4.1,
              }}>
              {mapName.toUpperCase()} {'·'} {modeLabel.toUpperCase()}
            </Text>
          </View>
          <View style={{ alignItems: 'flex-end' }}>
            {rankLabel ? (
              <Text
                style={{
                  color: rankColor ?? TEXT_PRIMARY,
                  fontSize: 31,
                  lineHeight: 35,
                  fontWeight: '900',
                  letterSpacing: 1.7,
                }}>
                {rankLabel}
              </Text>
            ) : null}
            {dateLabel || durationLabel ? (
              <Text
                style={{
                  marginTop: 14,
                  color: TEXT_MUTED,
                  fontSize: 24,
                  lineHeight: 29,
                  fontWeight: '700',
                }}>
                {dateLabel ? `${dateLabel} · ${durationLabel}` : durationLabel}
              </Text>
            ) : null}
          </View>
        </View>

        <View
          style={{
            marginTop: 42,
            flexDirection: 'row',
            justifyContent: 'flex-start',
            alignItems: 'center',
          }}>
          <Text
            allowFontScaling={false}
            numberOfLines={1}
            style={{
              width: 280,
              flexShrink: 0,
              color: result === 'win' ? accentColor : TEXT_PRIMARY,
              fontSize: 209,
              lineHeight: 230,
              fontWeight: '900',
              letterSpacing: -16.5,
              fontVariant: ['tabular-nums'],
              textAlign: 'left',
            }}>
            {myTeamScore}
          </Text>
          <Text
            allowFontScaling={false}
            numberOfLines={1}
            style={{
              width: 54,
              flexShrink: 0,
              marginHorizontal: 13,
              color: TEXT_PRIMARY,
              opacity: 0.3,
              fontSize: 101,
              lineHeight: 230,
              fontWeight: '300',
            }}>
            -
          </Text>
          <Text
            allowFontScaling={false}
            numberOfLines={1}
            style={{
              width: 280,
              flexShrink: 0,
              color: result === 'loss' ? accentColor : TEXT_PRIMARY,
              opacity: result === 'loss' ? 1 : 0.48,
              fontSize: 209,
              lineHeight: 230,
              fontWeight: '900',
              letterSpacing: -16.5,
              fontVariant: ['tabular-nums'],
              textAlign: 'left',
            }}>
            {enemyTeamScore}
          </Text>
        </View>
        <View
          style={{
            flexDirection: 'row',
            alignItems: 'center',
            paddingVertical: 18,
            paddingHorizontal: 22,
            marginBottom: 26,
            borderRadius: 24,
            backgroundColor: 'rgba(12, 16, 18, 0.64)',
            borderWidth: 1,
            borderColor: 'rgba(255, 255, 255, 0.14)',
          }}>
          <Image
            source={agentIconUrl}
            accessibilityLabel={agentName}
            style={{ width: 90, height: 90, borderRadius: 20, backgroundColor: withAlpha(accentColor, 0.2) }}
            contentFit="cover"
          />
          <View style={{ flex: 1, marginLeft: 18 }}>
            <View style={{ flexDirection: 'row', alignItems: 'baseline', gap: 9 }}>
              <Text style={{ color: TEXT_PRIMARY, fontSize: 37, lineHeight: 42, fontWeight: '900' }}>
                {playerTag.split('#')[0]}
              </Text>
              {playerTag.includes('#') ? (
                <Text style={{ color: TEXT_MUTED, fontSize: 24, lineHeight: 29, fontWeight: '600' }}>
                  #{playerTag.split('#').slice(1).join('#')}
                </Text>
              ) : null}
            </View>
            <Text
              style={{
                marginTop: 6,
                color: TEXT_MUTED,
                fontSize: 23,
                lineHeight: 28,
                fontWeight: '700',
                letterSpacing: 1.1,
              }}>
              {agentName}
            </Text>
          </View>
          <Text
            style={{
              color: TEXT_PRIMARY,
              fontSize: 64,
              lineHeight: 68,
              fontWeight: '800',
              fontVariant: ['tabular-nums'],
            }}>
            {kills}/{deaths}/{assists}
          </Text>
        </View>

        <SummaryCard stats={summaryStats} />

        <View style={{ flex: 1, justifyContent: 'flex-start', marginTop: 26 }}>
          {hasComparisons ? (
            <View style={{ marginBottom: 26 }}>
              <SectionLabel>{labels?.vsLobby ?? 'VS. LOBBY'}</SectionLabel>
              <ComparisonCard comparisons={comparisons!} />
            </View>
          ) : null}

          {visibleMoments.length > 0 ? (
            <View style={{ marginBottom: hasInsights ? 26 : 0 }}>
              <SectionLabel>{labels?.matchMoments ?? 'MATCH MOMENTS'}</SectionLabel>
              <View style={{ flexDirection: 'row', gap: 13 }}>
                {visibleMoments.slice(0, 2).map((moment, index) => (
                  <MomentCard key={`${moment.label}-${index}`} moment={moment} accentColor={accentColor} />
                ))}
              </View>
              {visibleMoments.length > 2 ? (
                <View style={{ flexDirection: 'row', gap: 13, marginTop: 13 }}>
                  {visibleMoments.slice(2, 4).map((moment, index) => (
                    <MomentCard key={`${moment.label}-${index + 2}`} moment={moment} accentColor={accentColor} />
                  ))}
                </View>
              ) : null}
            </View>
          ) : null}

          {hasInsights ? (
            <View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 13 }}>
              {visibleInsights.map((insight, index) => {
                const insightColor = insight.color ?? getBadgeColor(insight.tone, accentColor);
                return (
                  <View
                    key={`${insight.text}-${index}`}
                    style={{
                      paddingVertical: 12,
                      paddingHorizontal: 18,
                      borderRadius: 999,
                      backgroundColor: withAlpha(insightColor, 0.16),
                      borderWidth: 1,
                      borderColor: withAlpha(insightColor, 0.58),
                    }}>
                    <Text
                      style={{
                        color: insightColor,
                        fontSize: 19,
                        lineHeight: 23,
                        fontWeight: '800',
                        letterSpacing: 1.3,
                      }}>
                      {insight.text}
                    </Text>
                  </View>
                );
              })}
            </View>
          ) : null}

          <View
            style={{
              flexDirection: 'row',
              flexShrink: 0,
              justifyContent: 'flex-end',
              alignItems: 'center',
              marginTop: 22,
            }}>
            <BrandMark label={brandLabel} size={32} />
          </View>
        </View>
      </View>
    </View>
  );
}

export { MatchDetailPoster };
export type {
  MatchDetailPosterBadge,
  MatchDetailPosterBadgeTone,
  MatchDetailPosterInsight,
  MatchDetailPosterLabels,
  MatchDetailPosterComparison,
  MatchDetailPosterMetric,
  MatchDetailPosterMoment,
  MatchDetailPosterProps,
};
